# Generated by Django 5.0.4 on 2025-01-22 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_c', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Cliente')),
                ('nombreCompleto_c', models.CharField(max_length=100, verbose_name='Nombre Cliente')),
                ('email_c', models.CharField(max_length=100, verbose_name='Correo Cliente')),
                ('numeroTelefono_c', models.IntegerField(verbose_name='Numero Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id_t', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Trabajador')),
                ('nombreCompleto_t', models.CharField(max_length=100, verbose_name='Nombre Trabajador')),
                ('rut_t', models.IntegerField(verbose_name='Rut Trabajador')),
                ('numeroTelefono_t', models.IntegerField(verbose_name='Numero Trabajador')),
                ('email_t', models.CharField(max_length=100, verbose_name='Correo Trabajador')),
                ('contrasennia_t', models.CharField(max_length=25, verbose_name='Contraseña Trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_r', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Reserva')),
                ('lugarTatuaje_r', models.CharField(max_length=50, verbose_name='Lugar Tatuaje')),
                ('tamannio_r', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tamaño Tatuaje')),
                ('color_r', models.CharField(max_length=20, verbose_name='Color Tatuaje')),
                ('hora_r', models.DateTimeField()),
                ('descripcionTatuaje_r', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion Tatuaje')),
                ('referencia_r', models.ImageField(blank=True, null=True, upload_to='img/img_cliente/', verbose_name='Referencia Tatuaje')),
                ('cliente_r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente Reserva')),
                ('tatuador_r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trabajador', verbose_name='Tatuador Reserva')),
            ],
        ),
    ]
