# Generated by Django 5.0.7 on 2025-01-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='hora_r',
            field=models.DateTimeField(verbose_name='Fecha y Hora'),
        ),
    ]
