# Generated by Django 5.1.5 on 2025-01-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_reserva_hora_r'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id_c',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id de Cliente'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='id_r',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id Reserva'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='id_t',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id de Trabajador'),
        ),
    ]
