# Generated by Django 5.1.5 on 2025-01-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cliente_id_c_alter_reserva_id_r_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_p', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Producto')),
                ('nombre_p', models.CharField(max_length=100, verbose_name='Nombre Producto')),
                ('descripcion_p', models.TextField(verbose_name='Descripcion Producto')),
                ('precio_p', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Producto')),
                ('cantidad_p', models.PositiveIntegerField(verbose_name='Cantidad Producto')),
                ('imagen_p', models.ImageField(blank=True, null=True, upload_to='producto/', verbose_name='Imagen Producto')),
            ],
        ),
    ]
