# Generated by Django 5.1.5 on 2025-02-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteCuenta',
            fields=[
                ('id_cc', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Cliente')),
                ('nombreClienteCuenta', models.CharField(max_length=100, verbose_name='Nombre Completo Cliente')),
                ('emailClienteCuenta', models.CharField(max_length=100, unique=True, verbose_name='Correo Cliente')),
                ('telefonoClienteCuenta', models.IntegerField(verbose_name='Teléfono Cliente')),
                ('direccionClienteCuenta', models.CharField(max_length=100, verbose_name='Direccion Cliente')),
                ('contrasenniaaClienteCuenta', models.CharField(max_length=25, verbose_name='Contraseña Cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='email_t',
            field=models.CharField(max_length=100, unique=True, verbose_name='Correo Trabajador'),
        ),
    ]
